azure:
  x_user_id: ""
  max_token: 1068
  temperature: 0.73
  model: "gpt-4.1-2025-04-14"
  endpoint: "https://internal.apigateway.cibg.mashreqdev.com/mashreqtest/sandbox/azureopenai_msapi/v1/openai/deployments/openai-gpt4.1-ptu/chat/completions"

auth:
  scope: ""
  client_id: ""
  client_secret: ""
  token_url: "https://internal.apigateway.cibg.mashreqdev.com/mashreqtest/sandbox/oauth-v6/oauth2/token"

batch:
  max_threads: 10
  chunk_size: 1000

intents:
  - intent_id: 1
    intent_name: "Get Balance"
    description:
      "Tag an utterance to this intent when the customer wants to check the available or current balance of their
      account, debit card, credit card, loan, or deposit (e.g., “What's my balance?”, “Show remaining amount”). Ignore requests
      about reasons for low balance, failed/declined/on-hold transactions, fund transfers, or minimum balance requirements."

  - intent_id: 2
    intent_name: "Card Activation"
    description: "Tag this intent when the customer wants to activate their credit or debit card, including new, replacement, or reissued cards, or asks how to activate it via app, online banking, ATM, or phone banking. Ignore requests to apply for a new card, check delivery or application status, unlock or unblock a card, fix card issues, reset PIN, or activate their account or banking application."

  - intent_id: 3
    intent_name: "Get Transactions"
    description: "Tag utterances where customers request to check recent transactions linked to their account, card, loan, or deposit, including variations like viewing payments for a specific date or time range or asking why their balance is low. Exclude requests related to fees/charges, delayed/on-hold/declined transactions, refunds, or transaction reversal issues."

  - intent_id: 4
    intent_name: "Transfers and Payments"
    description: "Tag utterances where customers request to send money, including references to local/domestic or international transfers and terms like UAEFTS, RTGS, SWIFT, or Instant Transfer, as well as indirect phrases like “transfer funds” or “send money abroad.” Exclude requests to pay bills, check transfer status, complaints, enquiries about charges, limits, reversals/refunds, cash/cheque deposits or withdrawals, and setting up direct debits or standing instructions."

  - intent_id: 5
    intent_name: "View Account Status"
    description: "Tag requests where customers ask about the status of their new account application—whether it was reviewed, activated, or declined. Exclude requests to open an account, resolve opening issues, account usage problems, or status checks for other products/services like cards, loans, or banking apps."

groups:
  - group_id: 1
    intents: [1, 3, 12, 28, 23]
    group_name: "Account Information"
    description: "Balances, transactions, statements, Charges Fees And Profit and general account information."

  - group_id: 2
    intents: [5, 9, 10, 26]
    group_name: "Account Actions and Status"
    description: "Account status changes and requests such as block, unblock, and closure."

  - group_id: 3
    group_name: "Cards"
    intents: [6, 2, 15, 27, 29]
    description: "Debit card lifecycle including block, unblock, activation, delivery, and PIN reset."

report:
  generate_csv: true
  generate_html: true
  output_html: "report.html"

logging:
  level: "DEBUG"
  file: "batch.log"
